server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.rollout.io https://*.cloudbees.io; connect-src 'self' https://*.rollout.io https://*.cloudbees.io http://localhost:8081 http://localhost:8082 http://localhost:8083; style-src 'self' 'unsafe-inline'; img-src 'self' data:;" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
